include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    prefer_double_quotes: true
    unnecessary_this: false
    curly_braces_in_flow_control_structures: false
    constant_identifier_names: false