name: macieuls_coffee
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  dio: ^5.1.2
  json_annotation: ^4.8.1
  flutter_mobx: ^2.0.6+5
  intl: ^0.18.1
  mobx: ^2.1.4
  provider: ^6.0.5
  responsive_grid_list: ^1.3.2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  mobx_codegen: ^2.3.0
  json_serializable: ^6.7.0

flutter_launcher_icons:
  image_path: "assets/logo-web.png"
  web:
    generate: true
    image_path: "assets/logo-web.png"
    background_color: "#30BE00"
    theme_color: "#FFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900